version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.3.0

workflows:
  verify:
    jobs:
    - orb-tools/lint
    - orb-tools/pack:
        requires:
        - orb-tools/lint
    - orb-tools/publish-dev:
        orb-name: nemo157/rust
        requires:
        - orb-tools/pack
