parameters:
  checkout:
    type: boolean

  attach-workspace:
    type: boolean

  toolchain:
    type: string

  minimal-versions:
    type: boolean

  steps:
    type: steps

  persist-workspace:
    type: boolean

steps:
- when:
    condition: << parameters.checkout >>
    steps:
    - checkout
- when:
    condition: << parameters.attach-workspace >>
    steps:
    - attach-rust-workspace
- install-rustup
- rustup-update:
    toolchain: << parameters.toolchain >>
- when:
    condition: << parameters.minimal-versions >>
    steps:
    - rustup-update:
        toolchain: nightly
    - cargo:
        toolchain: nightly
        command: update -Z minimal-versions
- steps: << parameters.steps >>
- when:
    condition: << parameters.persist-workspace >>
    steps:
    - persist-target
